# .readthedocs.yaml
# Configuration file for Read the Docs.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python to use
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Tell Sphinx where to find the configuration file
sphinx:
  configuration: docs/conf.py

# Specify the path to your Python requirements file
python:
  install:
    - requirements: docs/requirements.txt
